Issue 2000 - Anax ppc64le support feature
open-horizon/anax pull request #2001
Opened 2020-09-01 11:31 UTC by jacob-rogers

2020-09-01 11:36 UTC, jacob-rogers commented
#2001

2020-09-01 16:18 UTC, jacob-rogers commented
@dabooz This PR is ready to be reviewed, thanks in advance!

2020-09-14 13:01 UTC, dabooz requested changes

2020-09-14 14:20 UTC, jacob-rogers commented on anax-in-container/Dockerfile_agbot.ubi.ppc64el
> +FROM registry.access.redhat.com/ubi8/ubi-minimal
Ok, I got it removed - only agent environment is going to be updated.

2020-09-14 14:20 UTC, jacob-rogers commented on Makefile
> +	if [[ $(arch) == "amd64" || $(arch) == "ppc64el" ]]; then \
Fixed.

2020-09-15 12:37 UTC, dabooz requested changes
The file rename of anax-in-container/Dockerfile_agbot.ubi.amd64 needs to be reverted also.

2020-09-15 12:56 UTC, jacob-rogers commented
> The file rename of anax-in-container/Dockerfile_agbot.ubi.amd64 needs to be reverted also.

@dabooz Reverted that, thanks.

2020-10-02 11:24 UTC, dabooz approved these changes

2020-10-02 15:25 UTC, merged