Issue #2016 - anax should invalidate the cache when an org is removed
open-horizon/anax pull request #2032
Opened 2020-09-10 20:32 UTC by MaxMcAdam

Signed-off-by: MaxMcAdam <max@fredcom.com>

2020-09-10 20:42 UTC, MaxMcAdam commented
The cache will drop the resources for an org when the agent gets a change message for the org with operation created or deleted. The created/modified operation means that there was a PUT request to the org in the exchange. This does not effect the cache because a new org cannot be created by a PUT request and the fields that can be changed by a PUT (or a PATCH) are not in the exchange cache.

2020-09-11 18:15 UTC, dabooz requested changes

2020-09-11 18:15 UTC, dabooz commented on exchange/cache.go
> +	} else if change.IsOrg() && (change.Operation == CHANGE_OPERATION_CREATED || change.Operation == CHANGE_OPERATION_DELETED) {
There are actually 4 events which can occur where everything in the org cache needs to be deleted. You handle 2 of them here. The other 2 are when the org is added to or removed from the agbot's served list. See this code: https://github.com/open-horizon/anax/blob/master/agreementbot/changes_worker.go#L270

2020-09-11 19:51 UTC, dabooz approved these changes

2020-09-11 19:54 UTC, merged