Issue 2038 - Dockerfile performance improvements
open-horizon/anax pull request #2078
Opened 2020-09-18 10:51 UTC by IntelliJIN

Reduced the number of layers by combining RUN commands.
Reduced the size of Go binaries by removing debugging information - flags-ldflags="-s -w".
Reduced the size of Go binaries by using Ultimate Packer for eXecutables (UPX). 
Added commands --no-install-recommends and rm -rf /var/lib/apt/lists/* to reduce image size.

Signed-off-by: Igor Kolinko <ikolin@softserveinc.com>

2020-11-10 17:04 UTC, linggao approved these changes

2020-11-10 17:06 UTC, linggao approved these changes

2020-11-10 17:12 UTC, linggao commented
Please resolve conflicts.

2020-11-10 18:41 UTC, linggao submitted a review, later dismissed
Please resolve the file conflicts.

2020-11-12 20:16 UTC, linggao requested changes
test failed. Please make sure the following works.
cd test
make realclean
make
make test

2020-11-12 21:54 UTC, dabooz requested changes

2020-11-12 21:54 UTC, dabooz commented on Makefile
> +upx:
Please make the use of upx optional, and by default not used.

2021-09-29 12:59 UTC, closed without merging