overhaul for new agent-install.sh tests and general test improvements
open-horizon/anax pull request #2082
Opened 2020-09-18 19:21 UTC by omega2733

Updated test suite that works with new changes to agent-install.sh. Includes the following:

- Updated to pull packages from artifactory instead of pkg-bluehorizon
- Removed 2 test cases for no longer supported cases (down-level agent installation support removed from agent-install.sh)
- Removed redundant assertions that could cause failures and test inconsistency (waiting for services to start when not necessary).
- Added support for local package use for tests that require only one version (all but test 6)
- Added support for only downloading a current version and skipping the agent-upgrade test (test 6). This test will run if a current version and previous version are provided to download.
- Added help menu to give some help context outside of git
- Fixed several test cases that failed or were inconsistent
- Fixed issue where terminal output would break due to some other functions in use
- Updated gitignore to ignore agent-install.crt/.cfg config files in agent-install/test/config & ../config/switch

2020-09-21 19:37 UTC, bmpotter requested changes

2020-09-22 12:35 UTC, omega2733 commented on agent-install/test/common.sh
> +    #    export CUR_VERSION=$(curl -s https://raw.githubusercontent.com/open-horizon/horizon-deb-packager/master/VERSION);
@bmpotter Right now it's commented out, this was some logic that would pull the latest version number to then initiate a default download of latest with the old code for bluehorizon packages. Right now you are required to specify local packages with -i or input a version number to pull from artifactory without automatically finding a default (temporary).

I've left the logic in for now so when we transition to the anax public packages I may be able to re-use some logic (but maybe not). The plan is to pull the latest from there by default in the future when it's available and allow to pull from artifactory with an option. If this isn't usable when I make that commit for the default logic, I'll completely remove this code when the change is made.

If we prefer to remove it completely now just let me know and I can do so, but it's not in use today.

2020-09-22 12:49 UTC, bmpotter commented on agent-install/test/common.sh
> +    #    export CUR_VERSION=$(curl -s https://raw.githubusercontent.com/open-horizon/horizon-deb-packager/master/VERSION);
Ok, that sounds good. I missed that it was commented out, sorry.

2020-09-22 12:49 UTC, bmpotter approved these changes

2020-09-22 13:03 UTC, merged