Fix "hzn dev service new" command to publish services with "public":false
open-horizon/anax pull request #2204
Opened 2020-11-20 04:31 UTC by clementkng

This commit partially addresses this [open-horizon/examples issue](https://github.com/open-horizon/examples/issues/356). Services should be created with `"public": false` so those outside the organizations can't see them by default.

Tested by locally building the hzn cli and making sure that the resulting horizon files have `"public": false` set on them.

Signed-off-by: Clement Ng <clementdng@gmail.com>

2020-11-30 16:52 UTC, dabooz commented
@clementdng please open an issue in the anax repo for this change, connect this PR to that issue, then attached the PR submitted label and move the issue into review/QA state.

2020-12-04 18:54 UTC, dabooz approved these changes

2020-12-04 20:05 UTC, clementkng commented
@dabooz thanks for reviewing this. Sorry, I think there's still some discussion in the [open-horizon/examples issue](https://github.com/open-horizon/examples/issues/356) so I'm not sure whether this is the exact behavior we want. I may convert this to a draft so it doesn't get accidentally merged in.

2021-01-05 20:07 UTC, linggao requested changes
This change broke the e2edev test. Please fix test/gov/hzn_dev_services.sh to make the service public.

2021-01-26 14:39 UTC, linggao commented
@clementkng Please see my comment above. Need to fix test/gov/hzn_dev_services.sh to make the services public.

2021-01-28 07:53 UTC, clementkng commented
@linggao thanks for reviewing! Right now, I'm working on understanding the e2edev test so I can make the test `Helloservice` service public. In the meantime, it seems that the original issue in the examples repo has changed direction, but I still think this PR is still helpful for Open Horizon users.

2021-01-28 15:52 UTC, linggao commented
@bmpotter do we still need this PR?

2021-01-29 12:12 UTC, bmpotter approved these changes

2021-01-29 12:13 UTC, bmpotter commented
> @bmpotter do we still need this PR?

@linggao yes we do

2021-02-02 01:20 UTC, clementkng commented
@linggao I was able to fix the `test/gov/hzn_dev_services.sh`

2021-02-02 14:32 UTC, linggao approved these changes

2021-02-02 14:34 UTC, merged