Issue 2249 - Allow UDS run as non-root user
open-horizon/anax pull request #2303
Opened 2021-02-15 18:38 UTC by LiilyZhang

Signed-off-by: zhangl <zhangl@us.ibm.com>

2021-02-22 22:41 UTC, dabooz requested changes

2021-02-22 22:41 UTC, dabooz commented on resource/authentication_manager.go
> +	currUser, err := user.Current()
Need comment here explaining the problem and how this fixes it. Line 87 isnt enough.

2021-02-23 00:40 UTC, LiilyZhang commented on ess/image/edge-sync-service-amd64/Dockerfile.ubi
> +RUN mkdir -p /edge-sync-service
No, this is not directly related to this issue. I found `make ess-docker-image` failed during my test. So this line is to fix `make ess-docker-image`

2021-02-23 18:20 UTC, dabooz approved these changes

2021-02-25 13:54 UTC, merged