Add e2edev tests support for ppc64le arch
open-horizon/anax pull request #2368
Opened 2021-03-09 19:56 UTC by jacob-rogers

Signed-off-by: Dmitry Gorbachev <dmitry.gorbachev@ru.ibm.com>

Co-authored-by: Yuri Pravosud <yuri.pravosud2@ibm.com>

Resolves #2366

2021-03-24 14:54 UTC, dabooz commented
@jacob-rogers Please open an issue for this PR and attach this PR to that issue so that we can review it.

2021-03-24 15:31 UTC, jacob-rogers commented
@dabooz Issue is opened and linked https://github.com/open-horizon/anax/issues/2366

2021-03-31 19:20 UTC, linggao commented on test/gov/run_kube.sh
> +$PWD/gov/input_files/k8s_deploy/node_ui.json
What are you trying to do here?

2021-03-31 19:29 UTC, linggao commented on test/gov/agbot_apitest.sh
> +  sed -i -e "s#__ARCH__#${ARCH}#g" in_file
Got the following errors here:
sed: can't read in_file: No such file or directory
sed: can't read in_file: No such file or directory
sed: can't read in_file: No such file or directory
sed: can't read in_file: No such file or directory
sed: can't read in_file: No such file or directory
sed: can't read in_file: No such file or directory

2021-03-31 19:49 UTC, linggao commented on test/gov/run_kube.sh
>  $cprefix microk8s.kubectl exec ${POD} -it -n ${NAME_SPACE} -- /usr/bin/hzn register -f /home/agentuser/node_ui.json -p e2edev@somecomp.com/sk8s -u root/root:${EXCH_ROOTPW}
Pass in ARCH to node_ui.json like this: 
````
$cprefix microk8s.kubectl exec ${POD} -it -n ${NAME_SPACE} -- env ARCH=${ARCH} /usr/bin/hzn register -f /home/agentuser/node_ui.json -p e2edev@somecomp.com/sk8s -u root/root:${EXCH_ROOTPW}
````

2021-04-01 17:43 UTC, linggao commented on test/gov/service_upgrading_downgrading_test.sh
> +        "image":"${CPU_IMAGE_NAME}:${CPU_IMAGE_TAG}"
Need a comma at the end.

2021-04-01 17:47 UTC, linggao commented
Please add the following code in gov-combined.sh at line 292 before `echo "TEST_PATTERNS=${TEST_PATTERNS}"`
````
for in_file in "/root/input_files/compcheck/*.json"
do
  sed -i -e "s#__ARCH__#${ARCH}#g" $in_file
done

for in_file in "/root/objects/*.json"
do
  sed -i -e "s#__ARCH__#${ARCH}#g" $in_file
done
````

2021-04-01 17:50 UTC, linggao commented on test/gov/resource_package.sh
> +		done
Please remove above code and see my last comment.

2021-04-01 17:51 UTC, linggao commented on test/gov/agbot_apitest.sh
> +
Please remove line 18-23 and see my last comment.

2021-04-01 17:51 UTC, linggao requested changes
per comments

2021-04-09 19:10 UTC, linggao commented
@jacob-rogers @ypravo could you please push again? The travis tests failed and I cannot restart the tests.

2021-04-09 21:21 UTC, jacob-rogers commented
> @jacob-rogers @ypravo could you please push again? The travis tests failed and I cannot restart the tests.

@linggao Done. And changes from your comments were also included. But please review all changes again if you can - few additional files needed to be fixed.

2021-04-09 23:53 UTC, linggao approved these changes

2021-04-09 23:53 UTC, merged