Fix service logging using service url field
open-horizon/anax pull request #2387
Opened 2021-03-21 06:36 UTC by codejaeger

Signed-off-by: codejaeger <mandaldebabrata123@gmail.com>

This is a possible fix to #2344. The solution solution relies on the authentication file generated as part of the service deployment. This is because I could not find any location where the mapping from the service url to the unique instance id could be found. Also, the primary need of logging using the service url to me seems to be to verify that the current running service matches with the service url which need not be the case when the parameter service url is not specified. I would be happy to make any changes based on suggestions. Thanks.

2021-03-23 16:44 UTC, dabooz requested changes

2021-03-23 16:44 UTC, dabooz commented on cli/hzn.go
> +	devServiceLogCmdServiceURL := devServiceLogCmd.Flag("service", msgPrinter.Sprintf("The the url field of the service definition whose log records should be displayed. Displays log records similar to
We want the hzn service log and hzn dev service log commands to have similar forms. I just updated to issue description to reflect what we want the user interface to look like.

2021-03-30 21:36 UTC, codejaeger commented
@dabooz if possible could you point me to the test file where I am supposed to add/change tests for the `hzn service log` command. Thanks

2021-04-08 18:04 UTC, dabooz requested changes
For tests, starting at this line: https://github.com/open-horizon/anax/blob/master/test/gov/gov-combined.sh#L385 is where the all the agent tests are performed. You will probably have to create a new script for the tests and then call the script at about line 502 which is at the end of current list of agent tests. Make sure you bracket the test invocation so that it can be skipped.

2021-04-08 18:04 UTC, dabooz commented on cli/service/service.go
> +					if containerName == strings.Split(service.Image, "@")[0] || (containerName == "" && len(deployment.Services) == 1) {
Why are you looking at the image name field?

2021-04-14 12:23 UTC, codejaeger commented on cli/hzn.go
> +	logServiceContainerName := serviceLogCmd.Flag("container", msgPrinter.Sprintf("The name of the container within the service whose log records should be displayed.")).Short('c').String()
@dabooz I added the deprecation statement for the `-s` flag in the help for `hzn dev service log`. I am not sure if this is the way to deprecate commands. Could you review it? Thanks.

2021-04-19 20:05 UTC, dabooz requested changes

2021-04-19 20:05 UTC, dabooz commented on cli/service/service.go
> +					cliutils.Fatal(cliutils.CLI_INPUT_ERROR, msgPrinter.Sprintf("Container %v is not running as part of service %v.", containerName, serviceName))
It is going to seem odd to the user when this message (or the one at line 140) comes out AFTER the message on line 109. Can we move the msgs at 109 down to after 159?

2021-04-22 11:59 UTC, dabooz commented on cli/hzn.go
> +	devServiceLogCmdServiceName := devServiceLogCmd.Flag("service", msgPrinter.Sprintf("(DEPRECATED) This flag is deprecated and is replaced by -c instead since there is an inconsistent usage of the fla
yes, this looks right

2021-05-04 19:02 UTC, dabooz requested changes

2021-06-07 19:37 UTC, dabooz requested changes

2021-06-07 19:37 UTC, dabooz commented on cli/service/service.go
> +		msgPrinter.Printf("Displaying log messages of container %v for service %v with service id %v.", containerName, name, instanceId)
This message comes out with a blank container name when the service's container is found but no containerName was provided as input. I think you will need to set containerName around line 144.

2021-06-07 19:37 UTC, dabooz commented on cli/service/service.go
> +		cliutils.Fatal(cliutils.CLI_INPUT_ERROR, msgPrinter.Sprintf("Could not find service %v running on the node.", containerName, serviceName))
There is only 1 substitution point but 2 variables provided. Remove the containerName variable.

2021-06-16 15:33 UTC, dabooz approved these changes

2021-06-16 15:40 UTC, merged