(Draft) Issue 2473 - Agent add /secret et. al. APIs, document APIs
open-horizon/anax pull request #2621
Opened 2021-07-06 16:06 UTC by LiilyZhang

Signed-off-by: zhangl <zhangl@us.ibm.com>

2021-07-13 13:38 UTC, dabooz requested changes

2021-07-13 13:38 UTC, dabooz commented on resource/secret_api.go
> +	getSecretsURL   = "/secrets"
I think we need to match the path of the other ESS APIs: /api/v1/secrets

2021-07-13 13:38 UTC, dabooz commented on container/container.go
> +			glog.V(5).Infof("Find for msInstance for service %s, serviceVersion %s, ms_instanceKey: %s. Token is: %s", serviceURL, sVer, msInstKey, cred.Token)
Logged the token again here, please remove this

2021-07-13 13:38 UTC, dabooz commented on resource/secret_api_authenticate.go
> +func extractAppKey(appKey string) (string, string, error) {
I dont think this function is called

2021-07-13 13:38 UTC, dabooz commented on persistence/secret_status.go
> +		w.MsInstKey, w.MsDefId, w.ESSToken, w.SecretsStatus)
display "********" for the token

2021-07-13 13:45 UTC, MaxMcAdam submitted a review, later dismissed

2021-07-14 14:15 UTC, LiilyZhang commented on resource/swagger-ui/LICENSE
> +Copyright 2019 SmartBear Software
I don't think swagger-ui is needed if we only want `swagger.json`. I can remove those

2021-07-14 14:18 UTC, LiilyZhang commented on persistence/secrets.go
> +	SecretsMap map[string]*PersistedServiceSecret
So the content inside SecretsMap will be modified because we will update the `TimeLastUpdated` all the time right?

2021-07-14 14:19 UTC, LiilyZhang commented on resource/secret_api_authenticate.go
> +func extractAppKey(appKey string) (string, string, error) {
Will remove it

2021-07-21 17:59 UTC, dabooz commented on persistence/secrets.go
> +	SecretsMap map[string]*PersistedServiceSecret
Right, and then the object is serialized into the database. This is ok AS LONG AS the callers of the function dont reference the object after the function returns.

2021-07-21 20:01 UTC, dabooz approved these changes

2021-07-21 20:05 UTC, merged