Issue 2962 - hzn mms object publish should support chunk uploading
open-horizon/anax pull request #2965
Opened 2022-01-10 19:51 UTC by LiilyZhang

Signed-off-by: zhangl <zhangl@us.ibm.com>

2022-01-11 15:03 UTC, linggao approved these changes

2022-01-19 16:01 UTC, dlarson04 requested changes

2022-01-19 16:26 UTC, LiilyZhang commented on cli/hzn.go
> +	mmsObjectPublishChunkUploadDataSize := mmsObjectPublishCmd.Flag("chunkSize", msgPrinter.Sprintf("The size of data chunk that will be published with. The default is 104856000 (10MB). Ignored if --chu
@dlarson04 will update the number

2022-01-19 16:28 UTC, LiilyZhang commented on config/constants.go
> +const HZN_FSS_MAX_CHUNK_SIZE = 5242880
@dlarson04 This is the chunksize of sync service inside agnet, between CSS and ESS.
The CLI chunk size is default in `hzn.go`, using the `.Default("104856000").Int()`
```
mmsObjectPublishChunkUploadDataSize := mmsObjectPublishCmd.Flag("chunkSize", msgPrinter.Sprintf("The size of data chunk that will be published with. The default is 104856000 (10MB). Ignored if --chunkUpload is not specified.")).Default("104856000").Int()
```

2022-01-19 18:54 UTC, dlarson04 approved these changes

2022-01-19 21:39 UTC, linggao approved these changes

2022-01-19 21:40 UTC, merged