Issue 3565 - Improve robustness of agent-install to retry on errors
open-horizon/anax pull request #3566
Opened 2022-12-12 16:05 UTC by LiilyZhang

Signed-off-by: zhangl <zhangl@us.ibm.com>

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [ ] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2022-12-12 21:20 UTC, johnwalicki requested changes
If this code snippet was a bash function, we would not need to include it twice in the code.

2022-12-13 13:20 UTC, dlarson04 requested changes

2022-12-13 13:20 UTC, dlarson04 commented on agent-install/agent-install.sh
I would suggest adding couple more changes to make this more robust.. You covered the cases where we download the packages but there are other curl usages that could fail... I suggest adding the following here

```
CURL_RETRY_PARMS="--retry 5 --retry-connrefused --retry-max-time 120"
```

and then in other cases that use curl that are not in your retry function, change
```
curl
```
to
```
curl ${CURL_RETRY_PARMS}
```

In the event that these could fail with some 50x errors, curl would retry

2022-12-13 17:44 UTC, dlarson04 approved these changes

2022-12-13 17:45 UTC, merged