Issue #3681 - Documentation: front matter directives and improve anax…
open-horizon/anax pull request #3682
Opened 2023-02-22 02:59 UTC by johnwalicki

…-in-container instructions

# Pull Request Template

## Description

Fixes #3681 
- Add front matter liquid directives for codeblocks
- whitespace around commands
- improve the anax-in-container documentation

## Type of change

- [x] This change requires a documentation update

## How Has This Been Tested?

Visit the rendered pages at https://open-horizon.github.io/docs/anax/docs/

## Checklist:

- [x] I have made corresponding changes to the documentation
- [x] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [x] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

2023-02-22 17:01 UTC, dlarson04 requested changes

2023-02-22 17:01 UTC, dlarson04 commented on docs/agent_container_manual_deploy.md
> +* Option 2 - If you have already installed the Horizon CLI package, it installed a `horizon-container` script onto your system.
how about 
```
If you have already installed the Horizon CLI package, it installed a `horizon-container` script onto your system that can be used to start the anax in container
```

2023-02-22 21:31 UTC, johnwalicki commented on docs/agent_container_manual_deploy.md
> +* Option 1 -The [agent-install instructions ](https://github.com/open-horizon/anax/tree/master/agent-install){:target="_blank"}{: .externalLink} provide a `--container` option to download and provisi
fixed

2023-02-22 21:32 UTC, johnwalicki commented on docs/agent_container_manual_deploy.md
> +There are several techniques to start the agent in a container:
good - fixed.

2023-02-22 21:34 UTC, johnwalicki commented on docs/agent_container_manual_deploy.md
> +* Option 2 - If you have already installed the Horizon CLI package, it installed a `horizon-container` script onto your system.
fixed.

2023-02-23 12:06 UTC, dlarson04 approved these changes

2023-02-23 12:50 UTC, merged