Issue 4031: Updated cluster_install.md page for Ubuntu 22.04 and simp…
open-horizon/anax pull request #4032
Opened 2024-04-09 18:11 UTC by joewxboy

…lified

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #4031 

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Ran locally in VM

## Additional Context (Please include any Screenshots/gifs if relevant)

...

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings
- [X] I have tagged the reviewers in a comment below incase my pull request is ready for a review
- [X] I have signed the commit message to agree to Developer Certificate of Origin (DCO) (to certify that you wrote or otherwise have the right to submit your contribution to the project.) by adding "--signoff" to my git commit command.

This closes issue #4031

2024-04-10 00:19 UTC, dlarson04 requested changes

2024-04-10 00:19 UTC, dlarson04 commented on docs/cluster_install.md
>      ```bash
not part of your PR but the examples above show setting the AGENT_NAMESPACE env variable.... but here we tell them if not set to use `openhorizon-agent`...  I think we should stick with the $AGENT_NAMESPACE syntax to be consistent throughout

2024-04-10 12:21 UTC, joewxboy commented on docs/cluster_install.md
>      ./agent-install.sh -D cluster -i anax: -c css: -k css: --namespace $AGENT_NAMESPACE --namespace-scoped
Step One at the top of the document has the user `sudo`.  We are assuming that this step is in the same terminal session.  Would it be helpful to have a reminder at this step?

2024-04-10 12:24 UTC, joewxboy commented
@dlarson04 I made most of your suggested changes.  Two I had replies to that you may want to review.

2024-04-10 13:09 UTC, euconnor approved these changes

2024-04-10 13:21 UTC, dlarson04 requested changes

2024-04-10 13:21 UTC, dlarson04 commented on docs/cluster_install.md
> +    **Note** If your server is not configured with the certificate, config, and agent files you will need to use the following alternative steps to install:
Yes... it always does

https://github.com/open-horizon/devops/blob/master/mgmt-hub/deploy-mgmt-hub.sh#L1385

2024-04-10 13:23 UTC, joewxboy commented on docs/cluster_install.md
>      ./agent-install.sh -D cluster -i anax: -c css: -k css: --namespace $AGENT_NAMESPACE --namespace-scoped
Adding a reminder in this section.

2024-04-10 13:32 UTC, joewxboy commented on docs/cluster_install.md
> +    **Note** If your server is not configured with the certificate, config, and agent files you will need to use the following alternative steps to install:
OK, removed that set of alternate instructions.

Added the missing Note colons. :)

2024-04-10 13:37 UTC, joewxboy commented
OK, I think I've made all the changes now @dlarson04 and @euconnor

2024-04-23 10:59 UTC, dlarson04 approved these changes

2024-04-23 13:07 UTC, merged