Improve output log clarity for palmctl uninstall openhorizon
open-horizon/anax pull request #4180
Opened 2024-12-04 14:56 UTC by Yummikko

## Description
Output log for 'palmctl uninstall openhorizon' command needs better clarity as it's confusing from a user perspective:
<img width="688" alt="Zrzut ekranu 2024-12-4 o 15 51 47" src="https://github.com/user-attachments/assets/d2228041-7741-4c29-8d27-5956dc47c681">

## Changes 
Added --ignore-not-found and -f flags to prevent errors related to missing resources.

Fixes # [MESH-3275](https://jsw.ibm.com/browse/MESH-3275)

- [ ] Bug fix (non-breaking change which fixes an issue)

2024-12-04 16:43 UTC, geforcelive2 approved these changes

2024-12-04 18:25 UTC, LiilyZhang commented
Please change the commit message to the following:
`Issue open-horizon#4181 - Bug: Output log for agent uninstall needs better clarity`

2024-12-04 18:26 UTC, LiilyZhang requested changes
Please change the commit message to the following:
`Issue open-horizon#4181 - Bug: Output log for agent uninstall needs better clarity`

2024-12-05 14:43 UTC, LiilyZhang approved these changes

2024-12-05 14:44 UTC, merged